language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t eddydocdoc/react-test-app -f ./frontend/Dockerfile.dev ./frontend


script:
  - docker run -e CI=true eddydocdoc/react-test-app npm run test

after_success:
  - docker build -t eddydocdoc/docker-frontend ./frontend
  - docker build -t eddydocdoc/docker-backend ./backend
  - docker build -t eddydocdoc/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push eddydocdoc/docker-frontend
  - docker push eddydocdoc/docker-backend
  - docker push eddydocdoc/docker-nginx